# Generated by Django 4.1.2 on 2022-12-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Descr', models.CharField(blank=True, max_length=30, null=True)),
                ('C_Image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
