# Generated by Django 4.1.2 on 2023-01-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0003_product_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_db',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
