# Generated by Django 4.1.2 on 2023-01-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0005_product_db_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=25, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Sub', models.CharField(blank=True, max_length=100, null=True)),
                ('Msg', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
